name: "Gemini Live Proxy"
description: "Proxy for Gemini Live API"
version: "1.0.1"
slug: "gemini_live_proxy"
init: false
arch:
  - aarch64
  - amd64
options:
  gemini_api_key: ""
schema:
  gemini_api_key: str
ports:
  7000/udp: 7000
  7000/tcp: 7000
map:
  - config:rw

hassio_api: true
hassio_role: homeassistant

homeassistant_api: true
auth_api: true
